name: Docker Image CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: bhargavreddy17
        password: Bhargav@17
    - name: Build the Docker image
      run: docker build -t bhargavreddy17/rgt-omni:testnodejs .
    - name: Push image to Docker Hub
      run: docker push bhargavreddy17/rgt-omni:testnodejs
      
    - name: Trigger deployment repo workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repository: bhargavreddy17/mycoookbooks
        event-type: trigger-deployment
        client-payload: '{"image_tag": "testnodejs"}'
