jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install Graphviz
      - name: Install Graphviz
        run: sudo apt-get install graphviz -y

      # Generate Workflow Graph
      - name: Generate Graph
        run: |
          ls -la .github/workflows  # List files in workflows directory
          dot -Tpng .github/workflows/*.yaml -o workflow_graph.png
        working-directory: ${{ github.workspace }}

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: workflow-graph
          path: workflow_graph.png
