name: Generate Workflow Graph

on:
  push:
    branches:
      - main

jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install Graphviz
      - name: Install Graphviz
        run: sudo apt-get install graphviz -y

      # Generate Workflow Graph
      - name: Generate Graph
        run: dot -Tpng .github/workflows/*.yml -o workflow_graph.png
        working-directory: ${{ github.workspace }}

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: workflow-graph
          path: workflow_graph.png
