name: Generate Workflow Graph

on:
  push:
    branches:
      - main

jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tpalsulich/github-action-graph@v1
        with:
          output-file: workflow_graph.dot
      - name: Convert to PNG
        run: dot -Tpng workflow_graph.dot -o workflow_graph.png
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: workflow-graph
          path: workflow_graph.png
